// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlForFSharp
{
    internal sealed partial class Vsix
    {
        public const string Id = "HtmlForFSharpLitTemplate";
        public const string Name = "Html for F# (Lit Template)";
        public const string Description = @"Hightlighting HTML String for (Lit) HTML String Templates";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Daniel Hardt";
        public const string Tags = "html, fable, fsharp, fable-lit, lit";
    }
}
