// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlForFSharp
{
    internal sealed partial class Vsix
    {
        public const string Id = "HtmlForFSharp.eb476a64-a1b5-41a8-b0e3-ec6f171abf6b";
        public const string Name = "HtmlForFSharp";
        public const string Description = @"HTML Highlighting in FSharp strings";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Daniel Hardt";
        public const string Tags = "html, fable, fsharp";
    }
}
